routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect('/home');
})->middleware('auth');

if (config('app.env') == 'local') {
    Route::get('/tester', function () {
        $page_title = 'Tester';

        return view('pages.tester', compact('page_title'));
    })->middleware('auth');
}

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'StockController@index')->name('home');
});

/* Item brand routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/item-brands/export', 'ItemBrandController@export')->name('item-brands.export');
    Route::post('/item-brands/import', 'ItemBrandController@import')->name('item-brands.import');
    Route::get('/item-brands/template', 'ItemBrandController@getTemplate')->name('item-brands.get-template');
});

/* Item group routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('item-groups/select', 'ItemGroupController@getSelect2Data')->name('item-groups.select2');
});

/* Company routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/companies/export', 'CompanyController@export')->name('companies.export');
    Route::get('/companies/import', 'CompanyController@import')->name('companies.import');
    Route::get('/companies/template', 'CompanyController@getTemplate')->name('companies.template');
    Route::get('/companies/type/{type}', 'CompanyController@getSelect2Data')->name('companies.select2');
});

/* Item routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/items/supplier/{id}', 'ItemController@getSelect2Data')->name('items.select2');
});

/* Unit routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/units/select', 'InventoryUnitController@getSelect2Data')->name('units.select2');
});

/* Selling routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/sales/invoice/{customer_id}/{item_id}', 'SaleController@getCustomerSellingPrice')->name('sales.customer-price');
});

Route::get('/sales/{id}/export', 'SaleController@export')->name('sales.export');
Route::get('/sales/print/{id}', 'SaleController@print')->name('sales.print');
Route::post('/sales/settlement/{id}', 'SaleController@settlement')->name('sales.settlement');

Route::group([ 'middleware' => 'auth', 'prefix' => 'ajax/', 'as' => 'ajax.' ], function(){
	Route::get('/fetch-id-permissions-for-role/{id}', 'RoleController@fetchIdPermissionsForRole');
	Route::post('/fetch-id-permissions-for-roles', 'RoleController@fetchIdPermissionsForRoles');
	Route::get('/fetch-id-suppliers-for-item/{id}', 'ItemController@fetchIdSuppliersForItem');
	Route::get('/fetch-inventory-units', 'InventoryUnitController@fetchInventoryUnits')->name('fetch_inventory_units');
	Route::get('/fetch-items', 'ItemController@fetchItems')->name('fetch_items');
	Route::get('/fetch-item-brands', 'ItemBrandController@fetchItemBrands')->name('fetch_item_brands');
	Route::get('/fetch-item-groups', 'ItemGroupController@fetchItemGroups')->name('fetch_item_groups');
	Route::get('/fetch-suppliers', 'SupplierController@fetchSuppliers')->name('fetch_suppliers');
	Route::get('/get-supplier-items/{id}', 'IncomingGoodController@getItem')->name('get-items');
	Route::get('/get-item', 'SaleController@getItem')->name('get-item');
	Route::get('/get-capital-prices/{id}', 'IncomingGoodController@getCapitalPrice')->name('get-capital-prices');
	Route::get('/get-selling-prices/{id}', 'SaleController@getSellingPrice')->name('get-selling-prices');
    Route::get('/get-default-selling-prices/{id}', 'SaleController@getDefaultSellingPrice')->name('get-default-selling-prices');
    Route::get('/get-stocks/{item_id}', 'StockController@getStock')->name('get-stocks');

	/* Fetching data */
	Route::get('/units/fetch', 'InventoryUnitController@fetchInventoryUnits')->name('get-units');
	Route::get('/units/get/{label}', 'InventoryUnitController@getUnit')->name('get-unit');

	/* Datatable data */
	Route::post('/items', 'ItemController@setDatatable')->name('items.data');
	Route::post('/customers', 'CustomerController@setDatatable')->name('customers.data');
	Route::post('/get-companies', 'CompanyController@setDatatable')->name('companies.data');
	Route::post('/get-invoices', 'SaleController@setDatatable')->name('sales.data');
	Route::post('/users/list', 'UserController@setDatatable')->name('users.data');
	Route::post('/units/list', 'InventoryUnitController@setDatatable')->name('units.data');
	Route::post('/incoming-goods/list', 'IncomingGoodController@setDatatable')->name('incoming-goods.data');

	Route::post('/get-inventory-units', 'InventoryUnitController@anyData')->name('inventory_units.data');
	Route::post('/get-item-brands', 'ItemBrandController@anyData')->name('item-brands.data');
	Route::post('/get-item-bundlings', 'ItemBundlingController@anyData')->name('item_bundlings.data');
	Route::post('/get-item-groups', 'ItemGroupController@anyData')->name('item-groups.data');
	Route::post('/get-item-stocks', 'ItemStockController@anyData')->name('item_stocks.data');
	Route::post('/get-roles', 'RoleController@anyData')->name('roles.data');
	Route::post('/get-stocks', 'StockController@setDatatable')->name('stocks.data');
	Route::post('/get-suppliers', 'SupplierController@setDatatable')->name('suppliers.data');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'items/', 'as' => 'items.' ], function() {
	Route::post('/choose-item', 'SaleController@chooseItem')->name('choose-item');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'incoming-goods/', 'as' => 'incoming-goods.' ], function() {
	Route::post('/choose-item', 'IncomingGoodController@chooseItem')->name('choose-item');
});

Route::group(['middleware' => 'auth'], function (){
	Route::resource('inventory-units', 'InventoryUnitController');
	Route::resource('items', 'ItemController');
	Route::resource('item-brands', 'ItemBrandController');
	Route::resource('item-bundlings', 'ItemBundlingController');
	Route::resource('item-groups', 'ItemGroupController');
	Route::resource('item-stocks', 'ItemStockController');
	Route::resource('roles', 'RoleController');
	Route::resource('stocks', 'StockController');
	Route::resource('suppliers', 'SupplierController');
	Route::resource('customers', 'CustomerController');
	Route::resource('users', 'UserController');
	Route::resource('companies', 'CompanyController');
	Route::resource('incoming-goods', 'IncomingGoodController');
	Route::resource('sales', 'SaleController');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'settings/', 'as' => 'settings.'], function () {
	Route::get('/', 'SettingController@index')->name('index');
	Route::post('/store', 'SettingController@store')->name('store');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'import/', 'as' => 'import.'], function () {
    Route::post('/items', 'ItemController@import')->name('items');
    Route::post('/item-groups', 'ItemGroupController@import')->name('item-groups');

    Route::post('/companies', 'CompanyController@import')->name('companies');
    Route::post('/units', 'InventoryUnitController@import')->name('units');
    Route::post('/stocks', 'StockController@import')->name('stocks');
    Route::post('/prices', 'DefaultPriceController@import')->name('prices');
    Route::post('/capital-price', 'CapitalPriceController@import')->name('capital-prices');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'database/', 'as' => 'database.'], function () {
    Route::post('/import/{type}', 'SettingController@import')->name('import');
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'id',
    	'name',
        'type',
        'address',
        'pic',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    // RELATION

    public function invoices()
    {
    	return $this->hasMany('App\Models\Invoice');
    }

    public function items()
    {
        return $this->hasMany('App\Models\Item', 'supplier_id');
    }

    // END OF RELATION
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Exports\CompanyExport;
use App\Exports\CompanyTemplate;
use App\Imports\CompanyImport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\Datatables\Datatables;

class CompanyController extends Controller
{
    /**
     * @var Object $brand_api API untuk pengelolaan brand.
     */
    private $company_api;

    /**
     *
     */
    public function __construct()
    {
        $this->company_api = new Api\ApiCompanyController;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect()->route('companies.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->company_api->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('companies.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return redirect()->route('companies.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->company_api->update($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->company_api->destroy($id);
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function setDatatable()
    {
        $models = $this->company_api->query();

        return Datatables::of($models)
            ->addColumn('type', function ($model) {
                switch ($model->type) {
                    case 'supplier':
                        $data = ucfirst($model->type);
                        break;

                    case 'customer':
                        $data = 'Pelanggan';
                        break;

                    default:
                        $data = 'Supplier dan juga customer';
                        break;
                }

                return $data;
            })
            ->addColumn('action', function ($model) {
                $button  = '';
                $button .= '<button type="button" class="btn btn-xs btn-link mb-xs mt-xs mr-xs" name="btn-destroy-company" data-id=' . $model->id . '><span class="fa fa-trash-o"></span> ' . ucwords(__('hapus')) . '</button>';
                $button .= '<button type="button" class="btn btn-xs btn-link mb-xs mt-xs mr-xs" name="btn-edit-company" data-id=' . $model->id . '><span class="fa fa-edit"></span> ' . ucwords(__('perbarui')) . '</button>';

                return $button;
            })
            ->make();
    }

    public function getTemplate()
    {
        return Excel::download(new CompanyTemplate, 'templat-kontak.xlsx');
    }

    public function export()
    {
        return Excel::download(new CompanyExport, 'daftar-kontak.xlsx');
    }

    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required'
        ]);

        $file = $request->file('file');

        Excel::import(new CompanyImport, $file, null, \Maatwebsite\Excel\Excel::XLSX);

        return redirect()->route('companies.index');
    }

    public function getSelect2Data($type)
    {
        $companies = $this->company_api->getByType($type);

        foreach ($companies as $key => $value) {
            if ($value->address !== null) {
                $data[] = [
                    'id'   => $value->id,
                    'text' => $value->name . ' - ' . $value->address,
                ];
            }
            else {
                $data[] = [
                    'id'   => $value->id,
                    'text' => $value->name,
                ];
            }
        }

        return $data;
    }
}

resources/views/companies/create.blade.php
{{-- companies/create.blade.php --}}

@component('components.modal',[
	'modal_id'    => 'modal-add-company',
	'modal_title' => 'tambah kontak'
])
	@slot('modal_body')
		<form method="post" action="{{ route('companies.store') }}" id="form-add-company">
			@csrf
			@include('companies._form')
		</form>
	@endslot

	@slot('modal_button')
		<button type="button" class="btn btn-default" data-dismiss="modal">{{ ucwords(__('batal')) }}</button>
		<button type="button" class="btn btn-primary" id="btn-add-company">{{ ucwords(__('simpan')) }}</button>
	@endslot
@endcomponent

@push('appscripts')
	<script type="text/javascript">
		$('#modal-add-company').ready(function () {
			/*
			 * Memodifikasi tampilan formulir penambahan resource
			 * ketika modal penambahan resource dimunculkan.
			 */
			 $('#modal-add-company').on('shown.bs.modal', function() {
				// Menghapus isian formulir.
				cleanModal('#form-add-company', true);
			});

			/* Penyimpanan data modal penambahan data. */
			$('#btn-add-company').click(function () {
				var form = $('#form-add-company');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function (response) {
                        $('#modal-add-company').modal('hide');

						table.ajax.reload();

						new PNotify({
							title: 'Sukses!',
							text: 'Data perusahaan berhasil ditambahkan.',
							type: 'success',
						});
					},
					error: function(response) {
						if (response.status == 422) {
							var errors = response.responseJSON;

							new PNotify({
								title: 'Peringatan!',
								text: 'Terdapat kesalahan pada data yang dimasukkan',
								type: 'warning'
							});

                            cleanModal('#form-add-company', false);

							$.each(errors.errors, function(col_val, msg) {
								$('#div-' + col_val).addClass('has-error');
								$('#label-' + col_val).html(msg[0]);
							});
						}
						else {
							systemError();
						}
					}
				});
			});
		});
	</script>
@endpush

resources/views/companies/destroy.blade.php
{{-- companies/destroy.blade.php --}}

@component('components.modal', [
	'modal_id'    => 'modal-destroy-company',
	'modal_title' => 'penghapusan kontak',
])
	@slot('modal_body')
		<form method="post" action="{{ route('companies.destroy', 0) }}" id="form-destroy-company">
			@csrf
			@method('DELETE')

			<p>Apakah kamu yakin ingin menghapus kontak <span id="company-name"></span>?</p>
	@endslot

	@slot('modal_button')
		<button type="button" class="btn btn-primary" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
		<button type="button" class="btn btn-default" id="btn-destroy-company"><span class="fa fa-trash-o"></span> {{ ucwords(__('hapus data')) }}</button>
	</form>
	@endslot
@endcomponent

@push('appscripts')
	<script type="text/javascript">
		$('#modal-destroy-company').ready(function () {
			/*
			 * Menampilkan jendela modal ketika tombol hapus resource ditekan.
			 */
			 $('#companies-table tbody').on('click', 'button[name="btn-destroy-company"]', function() {
                 // Ambil data company dari baris tombol yang ditekan.
				var data = table.row($(this).closest('tr')).data();

                $('#form-destroy-company #company-name').text(data.name);

				// Menetapkan URL untuk pemrosesan form.
				$('#form-destroy-company').attr('action', APP_URL + '/companies/' + $(this).data('id'));

				// Menampilkan jendela modal.
				$('#modal-destroy-company').modal('show');
			});

			/*
			 * Mengirim data pada form penghapusan resource saat tombol submisi ditekan.
			 */
			$('#btn-destroy-company').click(function () {
				var form = $('#form-destroy-company');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function(response) {
						$('#modal-destroy-company').modal('hide');

						if (response.status == 'success') {
							new PNotify({
								type:  'success',
								title: 'Berhasil!',
								text:  response.message,
							});

							table.ajax.reload();
						}
						else {
							new PNotify({
								type:  'warning',
								title: 'Peringatan!',
								text:  response.message,
							});
						}
					},

					error: function(response) {
                        console.log(response);
						systemError();
					}
				});
			});
		});
	</script>
@endpush

resources/views/companies/edit.blade.php
{{-- companies/edit.blade.php --}}

@component('components.modal',
['modal_id'   => 'modal-edit-company',
'modal_title' => 'Ubah Data Perusahaan',
])
	@slot('modal_body')
		<form method="POST" action="{{ route('companies.update', 0) }}" id="form-edit-company">
			@csrf
			@method('PUT')
			@include('companies._form')
	@endslot

	@slot('modal_button')
			<button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
			<button type="button" class="btn btn-primary" id="edit-company-btn">Simpan</button>
		</form>
	@endslot
@endcomponent

@push('appscripts')
    <script type="text/javascript">
        $('#modal-edit-company').ready(function () {
            /*
             * Menampilkan jendela modal ketika tombol edit resource ditekan.
             */
            $('#companies-table tbody').on('click', 'button[name="btn-edit-company"]', function () {
                cleanModal('#form-edit-company', false);

                // Ambil data supplier dari baris tombol yang ditekan.
                var data = table.row($(this).closest('tr')).data();

                // Mengisi nilai masing-masing bidang masukan formulir sesusai data yang diambil.
                $.each($('input, select, textarea', '#form-edit-company'), function () {
                    if ($(this).attr('id')) {
                        var id_element = $(this).attr('id');

                        if (data[id_element]) {
                            $('#' + id_element, '#form-edit-company').val(data[id_element]).trigger('change');
                        }
                        else {
                            $('#' + id_element, '#form-edit-company').val('').trigger('change');
						}
                    }
                });

                switch (data['type']) {
                    case 'Supplier':
                        $('#type-supplier', '#form-edit-company').prop('checked', true).val('supplier');
                        break;

                    case 'Pelanggan':
                        $('#type-customer', '#form-edit-company').prop('checked', true).val('customer');
                        break;

                    default:
                        $('#type-supplier', '#form-edit-company').prop('checked', true).val('supplier');
                        $('#type-customer', '#form-edit-company').prop('checked', true).val('customer');
                        break;
                }

				// Menetapkan URL untuk pemrosesan form.
				$('#form-edit-company').attr('action', APP_URL + '/customers/'+ $(this).data('id'));

				// Menampilkan jendela modal kepada pengguna.
				$('#modal-edit-company').modal('show');
            });

			/*
			 * Mengirim data pada form pengubahan resource saat tombol submisi ditekan.
			 */
			$('#edit-company-btn').click(function () {
				var form = $('#form-edit-company');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function(response) {
						$('#modal-edit-company').modal('hide');

						table.ajax.reload();

						new PNotify({
							type:  'success',
							title: 'Berhasil!',
							text:  'Informasi perusahaan ' + response.data.name + ' berhasil diperbarui.',
						});
					},

					error: function(response) {
						if (response.status == 422) {
							var errors = response.responseJSON;

							new PNotify({
								type:  'warning',
								title: 'Peringatan!',
								text:  'Terdapat kesalahan pada data yang dimasukkan',
							});

							cleanModal('#form-edit-company', false);

							$.each(errors.errors, function(col_val, msg) {
								$('#div-' + col_val, '#form-edit-company').addClass('has-error');
								$('#error- ' + col_val, '#form-edit-company').html(msg[0]);
							});
						}
						else {
                            systemError();
						}
					}
				});
			});
        });
    </script>
@endpush

resources/views/companies/import.blade.php
{{-- companies/import.blade.php --}}

@component('components.modal', [
    'modal_id'    => 'companies-import-modal',
    'modal_title' => 'impor kontak perusahaan'
])
    @slot('modal_body')
        <form action="{{ route('import.companies') }}" method="post" id="companies-import-form" enctype="multipart/form-data">
            @csrf

            <div class="form-group" id="div-file">
                <label for="file" class="col-sm-3 control-label text-right">
                    {{ ucfirst(__('file excel')) }}
                </label>

                <div class="col-sm-9">
                    <input type="file" name="file" id="file">
                </div>
            </div>
    @endslot

    @slot('modal_button')
            <button type="button" class="btn btn-default" data-dismiss="modal">
                <span class="fa fa-arrow-circle-left"></span>
                {{ ucwords(__('batal')) }}
            </button>

            <button type="submit" class="btn btn-primary" id="btn-import-item-brands">
                <span class="fa fa-database"></span>
                {{ ucwords(__('import')) }}
            </button>
        </form>
    @endslot
@endcomponent

resources/views/companies/index.blade.php
{{-- companies/index.blade.php --}}

@extends('layouts.dashboard', ['page_title' => 'manajemen kontak'])

@section('content')
    @component('components.panel', ['panel_title' => 'daftar kontak'])
        <!-- start: toolbar -->
        <div class="row mb-md">
            <!-- start: left toolbar -->
            <div class="col-md-6">
                <button class="btn btn-primary" data-toggle="modal" data-target="#modal-add-company" data-backdrop="static" data-keyboard="false">
                    <span class="fa fa-plus"></span>
                    {{ ucwords(__('tambah kontak')) }}
                </button>

                <div class="btn-group">
                    <a href="{{ route('suppliers.index') }}" class="btn btn-default">
                        <span class="fa fa-book"></span>
                        {{ ucwords(__('lihat supplier')) }}
                    </a>

                    <a href="{{ route('customers.index') }}" class="btn btn-default">
                        <span class="fa fa-book"></span>
                        {{ ucwords(__('lihat customer')) }}
                    </a>
                </div>
            </div>
            <!-- end: left toolbar -->

            <!-- start: right toolbar -->
            <div class="col-md-6 text-right">
                <div class="btn-group">
                    <a href="{{ route('sales.create') }}" class="btn btn-default">
                        <span class="fa fa-print"></span>
                        {{ ucwords(__('gawe faktur')) }}
                    </a>

                    <a href="{{ route('incoming-goods.create') }}" class="btn btn-default">
                        <span class="fa fa-truck"></span>
                        {{ ucwords(__('barang datang')) }}
                    </a>
                </div>

                <div class="btn-group">
                    <button id="company-template" class="btn btn-default" type="button">
                        <span class="fa fa-download"></span>
                        {{ ucwords(__('unduh templat')) }}
                    </button>

                    <button id="company-import" class="btn btn-default" type="button" data-toggle="modal" data-target="#companies-import-modal" data-backdrop="static" data-keyboard="false">
                        <span class="fa fa-upload"></span>
                        {{ ucwords(__('import data')) }}
                    </button>
                </div>
            </div>
            <!-- end: right toolbar -->
        </div>
        <!-- end: toolbar -->

        @component('components.datatable-ajax', [
			'table_id'      => 'companies',
			'table_headers' => ['nama kontak', 'alamat', 'kontak', 'jenis'],
			'condition'     => true,
			'data'          => [
				['name' => 'name', 'data' => 'name'],
				['name' => 'address', 'data' => 'address'],
				['name' => 'pic', 'data' => 'pic'],
				['name' => 'type', 'data' => 'type'],
			],
			'renders'       => [
                ['text_align' => 'text-right', 'column_target' => '5'],
            ],
            'default_order' => 1
        ])
            @slot('data_send_ajax')
            @endslot
        @endcomponent
	@endcomponent

	@include('companies.create')
	@include('companies.edit')
	@include('companies.destroy')
	@include('companies.import')
@endsection

@push('vendorstyles')
	<link href="{{ asset('assets/vendor/pnotify/pnotify.custom.css') }}" rel="stylesheet" style="text/css">
	<link href="{{ asset('assets/vendor/select2-4.0.8/css/select2.min.css') }}" rel="stylesheet" style="text/css">
	<link href="{{ asset('assets/vendor/select2-bootstrap/select2-bootstrap.min.css') }}" rel="stylesheet" style="text/css">
@endpush

@push('vendorscripts')
	<script src="{{ asset('assets/vendor/pnotify/pnotify.custom.js') }}" type="text/javascript"></script>
	<script src="{{ asset('assets/vendor/select2-4.0.8/js/select2.min.js') }}" type="text/javascript"></script>
@endpush

@push('appscripts')
	<script type="text/javascript">
		$(document).ready(function() {
            $('#company-template').on('click', function () {
                window.location.href = "{{ route('companies.template') }}";
            });

            /*
			$('#companies-table tbody').on('click', 'button[name="btn-show-company"]', function() {
				var url = APP_URL + '/companies/'+ $(this).data('id');

				$.ajax({
					url: url,
					method: 'GET',
					success: function(response) {
						$('.modal-body', '#modal-show-company').html(response);
					}
				});

				$('#modal-show-company').modal('show');
            });
            */

            /* Menampilkan modal ubah data. */
			// $('#companies-table tbody').on('click', 'button[name="btn-edit-company"]', function() {
			// 	var data = table.row($(this).closest('tr')).data();

			// 	$.each($('input, select, textarea', '#form-edit-company'), function() {
			// 		if ($(this).attr('id')) {
            //             var id_element = $(this).attr('id');

			// 			if (data[id_element]) {
			// 				$('#' + id_element, '#form-edit-company').val(data[id_element]).trigger('change');
			// 			}
			// 			else {
			// 				if ($(this).attr('type') != 'checkbox') {
			// 					$('#' + id_element, '#form-edit-company').val('').trigger('change');
			// 				}
			// 			}
			// 		}
			// 	});

			// 	$('select[name="company_id"]', '#form-edit-company').val(data['company_id']).trigger('change');

			// 	$('#form-edit-company').attr('action', APP_URL + '/companies/' + $(this).data('id'));

			// 	cleanModal('#form-edit-company', false);

			// 	$('#modal-edit-company').modal('show');
			// });

            /* Menyimpan data modal pengubahan data. */
			// $('#btn-edit-company').click(function () {
			// 	var form = $('#form-edit-company');

			// 	$.ajax({
			// 		url: form.attr('action'),
			// 		method: form.attr('method'),
			// 		data: form.serialize(),
			// 		success: function(response) {
            //             $('#modal-edit-company').modal('hide');

			// 			table.ajax.reload();

			// 			new PNotify({
			// 				title: 'Sukses!',
			// 				text: 'Data profil berhasil diubah.',
			// 				type: 'success',
			// 			});
			// 		},
			// 		error: function(response) {
			// 			if (response.status == 422) {
            //                 var errors = response.responseJSON;

			// 				new PNotify({
			// 					title: 'Peringatan!',
			// 					text: 'Terdapat kesalahan pada data yang dimasukkan',
			// 					type: 'warning'
            //                 });

            //                 cleanModal('#form-edit-company', false);

			// 				$.each(errors.errors, function(col_val, msg) {
			// 					$('#div_' + col_val, '#form-edit-company').addClass('has-error');
			// 					$('#label_' + col_val, '#form-edit-company').html(msg[0]);
			// 				});
			// 			}
			// 			else {
			// 				systemError();
			// 			}
			// 		}
			// 	});
			// });

            /* Menampilkan modal penghapusan data. */
			$('#companies-table tbody').on('click', 'button[name="btn-destroy-company"]', function() {
				$('#form-destroy-company').attr('action', APP_URL + '/companies/' + $(this).data('id'));
				$('#modal-destroy-company').modal('show');
			});

            /* Memproses data modal penghapusan. */
			$('#btn-destroy-company').click(function () {
				var form = $('#form-destroy-company');

				$.ajax({
					url: form.attr('action'),
					method: form.attr('method'),
					data: form.serialize(),
					success: function(response) {
						$('#modal-destroy-company').modal('hide');

						if (response.status == 'destroyed') {
							new PNotify({
								title: 'Sukses!',
								text: response.message,
								type: 'success',
							});

							table.ajax.reload();
						}
						else {
							new PNotify({
								title: 'Peringatan!',
								text: response.message,
								type: 'warning',
							});
						}
					},
					error: function(response) {
						systemError();
					}
				});
			});
        });
	</script>
@endpush

resources/views/companies/template.blade.php
<table>
    <thead>
        <tr>
            <th>{{ strtoupper('jenis') }}</th>
            <th>{{ strtoupper('nama') }}</th>
            <th>{{ strtoupper('pic') }}</th>
            <th>{{ strtoupper('alamat') }}</th>
        </tr>
    </thead>
</table>