routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect('/home');
})->middleware('auth');

if (config('app.env') == 'local') {
    Route::get('/tester', function () {
        $page_title = 'Tester';

        return view('pages.tester', compact('page_title'));
    })->middleware('auth');
}

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'StockController@index')->name('home');
});

/* Item brand routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/item-brands/export', 'ItemBrandController@export')->name('item-brands.export');
    Route::post('/item-brands/import', 'ItemBrandController@import')->name('item-brands.import');
    Route::get('/item-brands/template', 'ItemBrandController@getTemplate')->name('item-brands.get-template');
});

/* Item group routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('item-groups/select', 'ItemGroupController@getSelect2Data')->name('item-groups.select2');
});

/* Company routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/companies/export', 'CompanyController@export')->name('companies.export');
    Route::get('/companies/import', 'CompanyController@import')->name('companies.import');
    Route::get('/companies/template', 'CompanyController@getTemplate')->name('companies.template');
    Route::get('/companies/type/{type}', 'CompanyController@getSelect2Data')->name('companies.select2');
});

/* Item routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/items/supplier/{id}', 'ItemController@getSelect2Data')->name('items.select2');
});

/* Unit routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/units/select', 'InventoryUnitController@getSelect2Data')->name('units.select2');
});

/* Selling routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/sales/invoice/{customer_id}/{item_id}', 'SaleController@getCustomerSellingPrice')->name('sales.customer-price');
});

Route::get('/sales/{id}/export', 'SaleController@export')->name('sales.export');
Route::get('/sales/print/{id}', 'SaleController@print')->name('sales.print');
Route::post('/sales/settlement/{id}', 'SaleController@settlement')->name('sales.settlement');

Route::group([ 'middleware' => 'auth', 'prefix' => 'ajax/', 'as' => 'ajax.' ], function(){
	Route::get('/fetch-id-permissions-for-role/{id}', 'RoleController@fetchIdPermissionsForRole');
	Route::post('/fetch-id-permissions-for-roles', 'RoleController@fetchIdPermissionsForRoles');
	Route::get('/fetch-id-suppliers-for-item/{id}', 'ItemController@fetchIdSuppliersForItem');
	Route::get('/fetch-inventory-units', 'InventoryUnitController@fetchInventoryUnits')->name('fetch_inventory_units');
	Route::get('/fetch-items', 'ItemController@fetchItems')->name('fetch_items');
	Route::get('/fetch-item-brands', 'ItemBrandController@fetchItemBrands')->name('fetch_item_brands');
	Route::get('/fetch-item-groups', 'ItemGroupController@fetchItemGroups')->name('fetch_item_groups');
	Route::get('/fetch-suppliers', 'SupplierController@fetchSuppliers')->name('fetch_suppliers');
	Route::get('/get-supplier-items/{id}', 'IncomingGoodController@getItem')->name('get-items');
	Route::get('/get-item', 'SaleController@getItem')->name('get-item');
	Route::get('/get-capital-prices/{id}', 'IncomingGoodController@getCapitalPrice')->name('get-capital-prices');
	Route::get('/get-selling-prices/{id}', 'SaleController@getSellingPrice')->name('get-selling-prices');
    Route::get('/get-default-selling-prices/{id}', 'SaleController@getDefaultSellingPrice')->name('get-default-selling-prices');
    Route::get('/get-stocks/{item_id}', 'StockController@getStock')->name('get-stocks');

	/* Fetching data */
	Route::get('/units/fetch', 'InventoryUnitController@fetchInventoryUnits')->name('get-units');
	Route::get('/units/get/{label}', 'InventoryUnitController@getUnit')->name('get-unit');

	/* Datatable data */
	Route::post('/items', 'ItemController@setDatatable')->name('items.data');
	Route::post('/customers', 'CustomerController@setDatatable')->name('customers.data');
	Route::post('/get-companies', 'CompanyController@setDatatable')->name('companies.data');
	Route::post('/get-invoices', 'SaleController@setDatatable')->name('sales.data');
	Route::post('/users/list', 'UserController@setDatatable')->name('users.data');
	Route::post('/units/list', 'InventoryUnitController@setDatatable')->name('units.data');
	Route::post('/incoming-goods/list', 'IncomingGoodController@setDatatable')->name('incoming-goods.data');

	Route::post('/get-inventory-units', 'InventoryUnitController@anyData')->name('inventory_units.data');
	Route::post('/get-item-brands', 'ItemBrandController@anyData')->name('item-brands.data');
	Route::post('/get-item-bundlings', 'ItemBundlingController@anyData')->name('item_bundlings.data');
	Route::post('/get-item-groups', 'ItemGroupController@anyData')->name('item-groups.data');
	Route::post('/get-item-stocks', 'ItemStockController@anyData')->name('item_stocks.data');
	Route::post('/get-roles', 'RoleController@anyData')->name('roles.data');
	Route::post('/get-stocks', 'StockController@setDatatable')->name('stocks.data');
	Route::post('/get-suppliers', 'SupplierController@setDatatable')->name('suppliers.data');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'items/', 'as' => 'items.' ], function() {
	Route::post('/choose-item', 'SaleController@chooseItem')->name('choose-item');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'incoming-goods/', 'as' => 'incoming-goods.' ], function() {
	Route::post('/choose-item', 'IncomingGoodController@chooseItem')->name('choose-item');
});

Route::group(['middleware' => 'auth'], function (){
	Route::resource('inventory-units', 'InventoryUnitController');
	Route::resource('items', 'ItemController');
	Route::resource('item-brands', 'ItemBrandController');
	Route::resource('item-bundlings', 'ItemBundlingController');
	Route::resource('item-groups', 'ItemGroupController');
	Route::resource('item-stocks', 'ItemStockController');
	Route::resource('roles', 'RoleController');
	Route::resource('stocks', 'StockController');
	Route::resource('suppliers', 'SupplierController');
	Route::resource('customers', 'CustomerController');
	Route::resource('users', 'UserController');
	Route::resource('companies', 'CompanyController');
	Route::resource('incoming-goods', 'IncomingGoodController');
	Route::resource('sales', 'SaleController');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'settings/', 'as' => 'settings.'], function () {
	Route::get('/', 'SettingController@index')->name('index');
	Route::post('/store', 'SettingController@store')->name('store');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'import/', 'as' => 'import.'], function () {
    Route::post('/items', 'ItemController@import')->name('items');
    Route::post('/item-groups', 'ItemGroupController@import')->name('item-groups');

    Route::post('/companies', 'CompanyController@import')->name('companies');
    Route::post('/units', 'InventoryUnitController@import')->name('units');
    Route::post('/stocks', 'StockController@import')->name('stocks');
    Route::post('/prices', 'DefaultPriceController@import')->name('prices');
    Route::post('/capital-price', 'CapitalPriceController@import')->name('capital-prices');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'database/', 'as' => 'database.'], function () {
    Route::post('/import/{type}', 'SettingController@import')->name('import');
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use SoftDeletes;

    /**
     * List of mass-assigned model attributes
     *
     * @var string[]
     */
	protected $fillable = [
        'id',
        'item_group_id',
        'item_brand_id',
        'supplier_id',
        'unit_id',
        'name',
        'description'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

	// RELATION
	public function itemGroup()
	{
		return $this->belongsTo('App\Models\ItemGroup');
	}

	public function itemBrand()
	{
		return $this->belongsTo('App\Models\ItemBrand');
	}

    public function supplier()
    {
    	return $this->belongsTo('App\Models\Company');
    }

    public function unit()
    {
        return $this->belongsTo('App\Models\Unit');
    }

    public function capitalPrices()
    {
        return $this->hasMany('App\Models\CapitalPrice');
    }

    public function sellingPrices()
    {
        return $this->hasMany('App\Models\SellingPrice');
    }

    public function stocks()
    {
        return $this->hasMany('App\Models\Stock');
    }

    public function price()
    {
        return $this->hasMany('App\Models\DefaultPrice');
    }
    // END OF RELATION

    /**
     * Format description attribute
     *
     * Retrieve description attribute from database
     * then assign it the "-" character if there is empty.
     *
     * @return mixed
     */
    public function getDescriptionAttribute($value)
    {
    	if ($value) {
    		return $value;
        }
        else {
    		return '-';
    	}
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Imports\CompanyImport;
use App\Imports\ItemImport;
use App\Imports\ItemBrandImport;
use App\Imports\ItemGroupImport;
use App\Imports\UnitImport;
use App\Models\Item;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\Datatables\Datatables;

class ItemController extends Controller
{
    public function __construct(){
        $this->capital_api    = new \App\Http\Controllers\Api\ApiCapitalPriceController;
        $this->company_api    = new \App\Http\Controllers\Api\ApiCompanyController;
        $this->item_api       = new \App\Http\Controllers\Api\ApiItemController;
        $this->unit_api       = new \App\Http\Controllers\Api\ApiUnitController;
        $this->item_brand_api = new \App\Http\Controllers\Api\ApiItemBrandController;
        $this->item_group_api = new \App\Http\Controllers\Api\ApiItemGroupController;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['item_groups'] = $this->item_group_api->index();
        $data['item_brands'] = $this->item_brand_api->index();
        $data['suppliers']   = $this->company_api->getByType('supplier');
        $data['units']       = $this->unit_api->index();

        return view('items.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return redirect()->route('items.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item_group_id = $this->item_group_api->setOrCreate($request->item_group_id);
        $item_brand_id = $this->item_brand_api->setOrCreate($request->item_brand_id);
        $supplier_id   = $this->company_api->setOrCreate($request->supplier_id);

        $request['item_group_id'] = $item_group_id;
        $request['item_brand_id'] = $item_brand_id;
        $request['supplier_id']   = $supplier_id;

        return $this->item_api->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['item'] = $this->item_api->show($id)->getData()->data;

        return view('items._show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return redirect()->route('items.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->item_api->update($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->item_api->destroy($id);
    }

    /**
     * Generate datatable data.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function setDatatable()
    {
        $items = $this->item_api->query([
            'itemGroup',
            'itemBrand',
            'supplier',
            'capitalPrices',
            'sellingPrices'
        ]);

        return Datatables::of($items)
            ->addColumn('capital_price', function (Item $item) {
                $data = $item->capitalPrices->map(function ($price) {
                    return $price->value;
                })->last();

                if (isset($data)) {
                    return $data;
                }
                else {
                    return 0;
                }
            })
            ->addColumn('selling_price', function (Item $item) {
                $data = $item->sellingPrices->map(function ($price) {
                    return $price->value;
                })->last();

                $default = $item->price->map(function ($price) {
                    return $price->selling_price;
                })->last();

                if (isset($data)) {
                    return $data;
                }
                elseif (isset($default)) {
                    return $default;
                }
                else {
                    return 0;
                }
            })
            ->addColumn('action', function ($item) {
                $button  = '';
                $button .= '<button type="button" class="btn btn-link btn-xs mr-xs" name="btn-destroy-item" data-id="' . $item->id . '"><span class="fa fa-trash-o"></span> ' . ucwords(__('hapus')) . '</button>';
                $button .= '<button type="button" class="btn btn-link btn-xs mr-xs" name="btn-edit-item" data-id="' . $item->id . '"><span class="fa fa-edit"></span> ' . ucwords(__('perbarui')) . '</button>';
                $button .= '<button type="button" class="btn btn-link btn-xs" name="btn-show-item" data-id="' . $item->id . '"><span class="fa fa-eye"></span> ' . ucwords(__('lihat')) . '</button>';

                return $button;
            })
            ->make(true);
    }

    /**
     * Fetch id suppliers for item.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function fetchIdSuppliersForItem($id)
    {
        $data = $this->item_api->show($id)->getData()->data;

        return response()->json([
            'data' => $data
        ]);
    }

    /**
     * Fetch inventory unit
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function fetchItems()
    {
        $items = Item::pluck('name', 'id');

        return response()->json(['items' => $items]);
    }

    public function import(Request $request)
    {
        $request->validate([
            'item_group_file' => 'required',
            'item_brand_file' => 'required',
            'unit_file'       => 'required',
            'company_file'    => 'required',
        ]);

        $file = $request->file('file');
        $file = [
            'company'    => $request->file('company_file'),
            'item'       => $request->file('item_file'),
            'item_brand' => $request->file('item_brand_file'),
            'item_group' => $request->file('item_group_file'),
            'unit'       => $request->file('unit_file'),
        ];

        Excel::import(new ItemGroupImport, $file['item_group'], null, \Maatwebsite\Excel\Excel::XLSX);
        Excel::import(new ItemBrandImport, $file['item_brand'], null, \Maatwebsite\Excel\Excel::XLSX);
        Excel::import(new UnitImport, $file['unit'], null, \Maatwebsite\Excel\Excel::XLSX);
        Excel::import(new CompanyImport, $file['company'], null, \Maatwebsite\Excel\Excel::XLSX);
        Excel::import(new ItemImport, $file['item'], null, \Maatwebsite\Excel\Excel::XLSX);

        return redirect()->route('items.index');
    }

    public function getSelect2Data($supplier_id)
    {
        $items = $this->item_api->getBySupplier($supplier_id);

        foreach ($items as $key => $value) {
            $data[] = [
                'id'   => $value->id,
                'text' => $value->name,
            ];
        }

        return $data;
    }
}

resources/views/items/_form.blade.php
{{-- items/_form.blade.php --}}

<div class="form-group mt-lg" id="div-item_group_id">
	<label class="col-sm-3 control-label text-right">Kategori barang</label>

	<div class="col-sm-9">
		<select class="form-control" id="item_group_id" name="item_group_id">
			<option value="">Pilih kategori ...</option>

			@foreach ($item_groups as $item_group)
				<option value="{{ $item_group->id }}">{{ $item_group->name }}</option>
			@endforeach
		</select>

		<p class="help-block text-muted">Wajib diisi.</p>
		<p class="help-block text-muted text-left">Kamu dapat langsung mendaftarkan kategori barang di sini.</p>
		<p class="help-block text-error" id="error-item_group_id"></p>
	</div>
</div>

<div class="form-group mt-lg" id="div-item_brand_id">
	<label class="col-sm-3 control-label text-right">Merek barang</label>

	<div class="col-sm-9">
		<select class="form-control" id="item_brand_id" name="item_brand_id">
			<option value="">Pilih merek ...</option>

			@foreach ($item_brands as $brand)
				<option value="{{ $brand->id }}">{{ $brand->name }}</option>
			@endforeach
		</select>

		<p class="help-block text-muted">Wajib diisi.</p>
		<p class="help-block text-muted text-left">Kamu dapat langsung mendaftarkan merek barang di sini.</p>
		<p class="help-block text-error" id="error-item_brand_id"></p>
	</div>
</div>

<div class="form-group mt-lg" id="div-supplier_id">
	<label class="col-sm-3 control-label text-right">Supplier</label>

	<div class="col-sm-9">
		<select class="form-control" id="supplier_id" name="supplier_id">
			<option value="">Pilih supplier ...</option>

			@foreach ($suppliers as $supplier)
				<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>
			@endforeach
		</select>

		<span class="help-block text-muted">Wajib diisi.</span>
		<span class="help-block text-muted">
			Kamu dapat mendaftarkan supplier baru di halaman daftar supplier.
			<a href="{{ route('suppliers.index') }}">Klik di sini untuk membuka halaman daftar supplier.</a>
			Atau gunakan tombol yang tersedia di atas tabel daftar produk.
		</span>
		<span class="help-block text-error" id="error-supplier_id"></span>
	</div>
</div>

<hr>

<div class="form-group mt-lg" id="div-name">
	<label class="col-sm-3 control-label text-right">Nama barang</label>

	<div class="col-sm-9">
		<input type="text" id="name" name="name" class="form-control" required>

		<span class="help-block text-muted">Wajib diisi</span>
		<span class="help-block text-error" id="error-name"></span>
	</div>
</div>

<div class="form-group mt-lg" id="div-unit_id">
	<label class="col-sm-3 control-label text-right">Satuan</label>

	<div class="col-sm-9">
        <div class="row">
            <div class="col-md-7">
                <select class="form-control" id="unit_id" name="unit_id">
                    <option></option>
                </select>
            </div>

            <div class="col-md-5">
                <button type="button" class="btn btn-block btn-default btn-model-add" id="unit-addition-button" data-toggle="modal" data-target="#modal-add-inventory-unit" data-backdrop="static" data-keyboard="false">
                    <span class="fa fa-plus"></span>
                    {{ ucwords(__('tambah satuan')) }}
                </button>
            </div>
        </div>

		<p class="help-block text-muted">Wajib diisi.</p>
        <span class="help-block text-error" id="error-unit_id"></span>
	</div>
</div>

<hr>

<div class="form-group mt-lg" id="div-description">
	<label class="col-sm-3 control-label text-right">Catatan</label>

	<div class="col-sm-9">
		<textarea name="description" id="description" class="form-control"></textarea>

		<span class="help-block text-error" id="error-description"></span>
	</div>
</div>

resources/views/items/_show.blade.php
{{-- items/_show.blade.php --}}

<h3 class="text-semibold">{{ strtoupper($item->name) }}</h3>

<p class="text-muted m-none">Merek: {{ $item->item_brand->name }}</p>

<p>Produk ini disuplai oleh <strong>{{ $item->supplier->name }}</strong>
    yan masuk sebagai kategori produk <strong>{{ $item->item_group->name }}</strong>.</p>

<hr>

<h4>Catatan</h4>
<p class="mt-sm">{{ $item->description }}</p>

resources/views/items/create.blade.php
{{-- items/create.blade.php --}}

@component('components.modal', [
	'modal_id'    => 'modal-add-item',
	'modal_title' => 'tambah produk baru'
])
	@slot('modal_body')
		<form action="{{ route('items.store') }}" method="post" id="form-add-item">
			@csrf
			@include('items._form')
		</form>
	@endslot

	@slot('modal_button')
		<button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
		<button type="submit" class="btn btn-primary" id="btn-add-item"><span class="fa fa-save"></span> {{ ucwords(__('simpan')) }}</button>
	@endslot
@endcomponent

@push('appscripts')
	<script type="text/javascript">
		/*
		 * Memodifikasi tampilan formulir penambahan resource
		 * ketika modal penambahan resource dimunculkan.
		 */
		$('#modal-add-item').on('shown.bs.modal', function() {
			clearForm($('#modal-add-item #form-add-item'));
            disableEvents('#form-add-item');

            $(this).find('select').each(function () {
                switch ($(this).attr('id')) {
                    case 'item_group_id':
                        selectItemGroup($('#form-add-item #item_group_id'), $('#form-add-item'));
                        break;

					case 'unit_id':
                        selectUnit($('#form-add-item #unit_id'), $('#form-add-item'));
                        break;

					case 'supplier_id':
                        selectCompany('supplier', $(this), $('#form-add-item'));
						break;

					default:
						$(this).select2({
							dropdownParent: $('#form-add-item'),
							tags: true,
							placeholder: 'Pilih dari daftar',
							allowClear: true
						});
						break;
				}
			});
		});

		/*
 		 * Mengirim data pada form penambahan resource saat tombol submisi ditekan.
		 */
		$('#btn-add-item').click(function() {
			var modal = $('#modal-add-item');
			var form  = $('#form-add-item');

			$.ajax({
				url:    form.attr('action'),
				method: form.attr('method'),
				data:   form.serialize(),

				success: function (response) {
					generateSuccess(modal, response.data.name + ' berhasil ditambahkan dalam daftar produk.');
				},

				error: function (response) {
					if (response.status == 422) {
						generateError('#form-add-item', response.responseJSON);
					}
					else {
						systemError();
					}
				}
			});
		});
	</script>
@endpush

resources/views/items/import.blade.php
{{-- items/import.blade.php --}}

@component('components.modal', [
    'modal_id'    => 'item-import-modal',
    'modal_title' => 'impor produk'
])
    @slot('modal_body')
        <form action="{{ route('import.items') }}" method="post" id="item-import-form" enctype="multipart/form-data">
            @csrf

            <div class="form-group" id="div-file">
                <label for="file" class="col-sm-3 control-label text-right">
                    {{ ucfirst(__('file excel')) }}
                </label>

                <div class="col-sm-9">
                    <input type="file" name="file" id="file">
                </div>
            </div>
    @endslot

    @slot('modal_button')
            <button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
            <button type="submit" class="btn btn-primary" id="btn-import-item"><span class="fa fa-database"></span> {{ ucwords(__('import')) }}</button>
        </form>
    @endslot
@endcomponent

resources/views/items/index.blade.php
{{-- items/index.blade.php --}}

@extends('layouts.dashboard', ['page_title' => 'manajemen produk'])

@section('content')
	<p class="lead">
		Di sini kamu dapat mengatur informasi produk yang kamu miliki.
		Kamu dapat melihat daftar produk, menambahkan produk,
		memperbarui informasi produk, dan menghapus produk yang ada.
	</p>

    @component('components.panel', ['panel_title' => 'daftar barang'])
        <!-- start: toolbar -->
        <div class="row mb-md">
            <!-- start: left toolbar -->
            <div class="col-md-6">
                <button class="btn btn-primary" data-toggle="modal" data-target="#modal-add-item" data-backdrop="static" data-keyboard="false">
                    <span class="fa fa-plus"></span>
                    {{ ucwords(__('tambah barang')) }}
                </button>

                <div class="btn-group">
                    <a href="{{ route('sales.create') }}" class="btn btn-default">
                        <span class="fa fa-print"></span>
                        {{ ucwords(__('gawe faktur')) }}
                    </a>

                    <a href="{{ route('incoming-goods.create') }}" class="btn btn-default">
                        <span class="fa fa-truck"></span>
                        {{ ucwords(__('barang datang')) }}
                    </a>
                </div>
            </div>
            <!-- end: left toolbar -->

            <!-- start: right toolbar -->
            <div class="col-md-6 text-right">
                <div class="btn-group">
                    <button class="btn btn-default btn-model-add" data-toggle="modal" data-target="#supplier-addition-modal" data-backdrop="static" data-keyboard="false">
                        <span class="fa fa-plus"></span>
                        {{ ucwords(__('tambah supplier')) }}
                    </button>

                    <button class="btn btn-default btn-model-add" id="unit-addition-button" data-toggle="modal" data-target="#modal-add-inventory-unit" data-backdrop="static" data-keyboard="false">
                        <span class="fa fa-plus"></span>
                        {{ ucwords(__('tambah satuan')) }}
                    </button>
                </div>
            </div>
            <!-- end: right toolbar -->
        </div>
        <!-- end: toolbar -->

		@component('components.datatable-ajax', [
			'table_id'      => 'items',
			'table_headers' => ['kategori produk', 'merek produk', 'supplier', 'nama produk'],
			'condition'     => true,
			'data'          => [
				['name' => 'itemGroup.name', 'data' => 'item_group.name'],
				['name' => 'itemBrand.name', 'data' => 'item_brand.name'],
				['name' => 'supplier.name', 'data' => 'supplier.name'],
				['name' => 'name', 'data' => 'name'],
			],
			'default_order' => 4
		])
				@slot('data_send_ajax')
				@endslot
		@endcomponent
	@endcomponent

	@include('items.create')
	@include('items.show')
	@include('items.edit')
	@include('items.destroy')
	@include('items.import')
	@include('companies.supplier.create')
	@include('inventory-units.create')
@endsection

@push('vendorstyles')
	<link href="{{ asset('assets/vendor/pnotify/pnotify.custom.css') }}" rel="stylesheet" type="text/css">
	<link href="{{ asset('assets/vendor/select2-4.0.8/css/select2.min.css') }}" rel="stylesheet" type="text/css">
	<link href="{{ asset('assets/vendor/select2-bootstrap/select2-bootstrap.min.css') }}" rel="stylesheet" type="text/css">
@endpush

@push('vendorscripts')
	<script src="{{ asset('assets/vendor/pnotify/pnotify.custom.js') }}" type="text/javascript"></script>
	<script src="{{ asset('assets/vendor/select2-4.0.8/js/select2.min.js') }}" type="text/javascript"></script>
@endpush

@prepend('appscripts')
	<script type="text/javascript">
		$(document).ready(function () {
			$.fn.select2.defaults.set( "theme", "bootstrap" );

			$('#supplier-addition-modal, #modal-add-inventory-unit').on('hide.bs.modal', function() {
				location.reload();
			});
		});
	</script>
@endprepend