routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect('/home');
})->middleware('auth');

if (config('app.env') == 'local') {
    Route::get('/tester', function () {
        $page_title = 'Tester';

        return view('pages.tester', compact('page_title'));
    })->middleware('auth');
}

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'StockController@index')->name('home');
});

/* Item brand routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/item-brands/export', 'ItemBrandController@export')->name('item-brands.export');
    Route::post('/item-brands/import', 'ItemBrandController@import')->name('item-brands.import');
    Route::get('/item-brands/template', 'ItemBrandController@getTemplate')->name('item-brands.get-template');
});

/* Item group routes. */
Route::group(['middleware' => ['auth']], function () {
    Route::get('item-groups/select', 'ItemGroupController@getSelect2Data')->name('item-groups.select2');
});

/* Company routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/companies/export', 'CompanyController@export')->name('companies.export');
    Route::get('/companies/import', 'CompanyController@import')->name('companies.import');
    Route::get('/companies/template', 'CompanyController@getTemplate')->name('companies.template');
    Route::get('/companies/type/{type}', 'CompanyController@getSelect2Data')->name('companies.select2');
});

/* Item routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/items/supplier/{id}', 'ItemController@getSelect2Data')->name('items.select2');
});

/* Unit routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/units/select', 'InventoryUnitController@getSelect2Data')->name('units.select2');
});

/* Selling routes */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/sales/invoice/{customer_id}/{item_id}', 'SaleController@getCustomerSellingPrice')->name('sales.customer-price');
});

Route::get('/sales/{id}/export', 'SaleController@export')->name('sales.export');
Route::get('/sales/print/{id}', 'SaleController@print')->name('sales.print');
Route::post('/sales/settlement/{id}', 'SaleController@settlement')->name('sales.settlement');

Route::group([ 'middleware' => 'auth', 'prefix' => 'ajax/', 'as' => 'ajax.' ], function(){
	Route::get('/fetch-id-permissions-for-role/{id}', 'RoleController@fetchIdPermissionsForRole');
	Route::post('/fetch-id-permissions-for-roles', 'RoleController@fetchIdPermissionsForRoles');
	Route::get('/fetch-id-suppliers-for-item/{id}', 'ItemController@fetchIdSuppliersForItem');
	Route::get('/fetch-inventory-units', 'InventoryUnitController@fetchInventoryUnits')->name('fetch_inventory_units');
	Route::get('/fetch-items', 'ItemController@fetchItems')->name('fetch_items');
	Route::get('/fetch-item-brands', 'ItemBrandController@fetchItemBrands')->name('fetch_item_brands');
	Route::get('/fetch-item-groups', 'ItemGroupController@fetchItemGroups')->name('fetch_item_groups');
	Route::get('/fetch-suppliers', 'SupplierController@fetchSuppliers')->name('fetch_suppliers');
	Route::get('/get-supplier-items/{id}', 'IncomingGoodController@getItem')->name('get-items');
	Route::get('/get-item', 'SaleController@getItem')->name('get-item');
	Route::get('/get-capital-prices/{id}', 'IncomingGoodController@getCapitalPrice')->name('get-capital-prices');
	Route::get('/get-selling-prices/{id}', 'SaleController@getSellingPrice')->name('get-selling-prices');
    Route::get('/get-default-selling-prices/{id}', 'SaleController@getDefaultSellingPrice')->name('get-default-selling-prices');
    Route::get('/get-stocks/{item_id}', 'StockController@getStock')->name('get-stocks');

	/* Fetching data */
	Route::get('/units/fetch', 'InventoryUnitController@fetchInventoryUnits')->name('get-units');
	Route::get('/units/get/{label}', 'InventoryUnitController@getUnit')->name('get-unit');

	/* Datatable data */
	Route::post('/items', 'ItemController@setDatatable')->name('items.data');
	Route::post('/customers', 'CustomerController@setDatatable')->name('customers.data');
	Route::post('/get-companies', 'CompanyController@setDatatable')->name('companies.data');
	Route::post('/get-invoices', 'SaleController@setDatatable')->name('sales.data');
	Route::post('/users/list', 'UserController@setDatatable')->name('users.data');
	Route::post('/units/list', 'InventoryUnitController@setDatatable')->name('units.data');
	Route::post('/incoming-goods/list', 'IncomingGoodController@setDatatable')->name('incoming-goods.data');

	Route::post('/get-inventory-units', 'InventoryUnitController@anyData')->name('inventory_units.data');
	Route::post('/get-item-brands', 'ItemBrandController@anyData')->name('item-brands.data');
	Route::post('/get-item-bundlings', 'ItemBundlingController@anyData')->name('item_bundlings.data');
	Route::post('/get-item-groups', 'ItemGroupController@anyData')->name('item-groups.data');
	Route::post('/get-item-stocks', 'ItemStockController@anyData')->name('item_stocks.data');
	Route::post('/get-roles', 'RoleController@anyData')->name('roles.data');
	Route::post('/get-stocks', 'StockController@setDatatable')->name('stocks.data');
	Route::post('/get-suppliers', 'SupplierController@setDatatable')->name('suppliers.data');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'items/', 'as' => 'items.' ], function() {
	Route::post('/choose-item', 'SaleController@chooseItem')->name('choose-item');
});

Route::group([ 'middleware' => 'auth', 'prefix' => 'incoming-goods/', 'as' => 'incoming-goods.' ], function() {
	Route::post('/choose-item', 'IncomingGoodController@chooseItem')->name('choose-item');
});

Route::group(['middleware' => 'auth'], function (){
	Route::resource('inventory-units', 'InventoryUnitController');
	Route::resource('items', 'ItemController');
	Route::resource('item-brands', 'ItemBrandController');
	Route::resource('item-bundlings', 'ItemBundlingController');
	Route::resource('item-groups', 'ItemGroupController');
	Route::resource('item-stocks', 'ItemStockController');
	Route::resource('roles', 'RoleController');
	Route::resource('stocks', 'StockController');
	Route::resource('suppliers', 'SupplierController');
	Route::resource('customers', 'CustomerController');
	Route::resource('users', 'UserController');
	Route::resource('companies', 'CompanyController');
	Route::resource('incoming-goods', 'IncomingGoodController');
	Route::resource('sales', 'SaleController');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'settings/', 'as' => 'settings.'], function () {
	Route::get('/', 'SettingController@index')->name('index');
	Route::post('/store', 'SettingController@store')->name('store');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'import/', 'as' => 'import.'], function () {
    Route::post('/items', 'ItemController@import')->name('items');
    Route::post('/item-groups', 'ItemGroupController@import')->name('item-groups');

    Route::post('/companies', 'CompanyController@import')->name('companies');
    Route::post('/units', 'InventoryUnitController@import')->name('units');
    Route::post('/stocks', 'StockController@import')->name('stocks');
    Route::post('/prices', 'DefaultPriceController@import')->name('prices');
    Route::post('/capital-price', 'CapitalPriceController@import')->name('capital-prices');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'database/', 'as' => 'database.'], function () {
    Route::post('/import/{type}', 'SettingController@import')->name('import');
});

app/Models/ItemGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ItemGroup extends Model
{
    use SoftDeletes;

    protected $fillable = ['id', 'parent_id', 'name', 'description'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    // RELATION
    public function items()
    {
        return $this->hasMany('App\Models\Item');
    }

    public function parent()
    {
    	return $this->belongsTo('App\Models\ItemGroup');
    }
    // END RELATION


    // ACCESSOR
    public function getDescriptionAttribute($value)
    {
    	if ($value) {
    		return $value;
    	}else{
    		return '-';
    	}
    }
}

app/Http/Controllers/ItemGroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Api\ApiItemGroupController;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Yajra\Datatables\Datatables;

class ItemGroupController extends Controller
{
    /**
     * @var Object $brand_api API untuk pengelolaan brand.
     */
    private $item_group_api;

    /**
     *
     */
    public function __construct()
    {
        $this->item_group_api = new ApiItemGroupController;
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function anyData()
    {
        $models = $this->item_group_api->query();

        return Datatables::of($models)
            ->addColumn('action', function ($model) {
                $button  = '';
                $button .= '<button type="button" class="btn btn-link btn-xs mb-xs mt-xs mr-xs" name="btn-destroy-item-group" data-id=' . $model->id . '><span class="fa fa-trash-o"></span> ' . ucwords(__('hapus')) . '</button>';
                $button .= '<button type="button" class="btn btn-link btn-xs mb-xs mt-xs mr-xs" name="btn-edit-item-group" data-id=' . $model->id . '><span class="fa fa-edit"></span> ' . ucwords(__('perbarui')) . '</button>';
                $button .= '<button type="button" class="btn btn-link btn-xs mb-xs mt-xs mr-xs" name="btn-show-item-group" data-id=' . $model->id . '><span class="fa fa-eye"></span> ' . ucwords(__('lihat')) . '</button>';

                return $button;
            })
            ->filterColumn('parent_name', function ($query, $keyword){
                $query->whereRaw('parent.name LIKE ?', ["%$keyword%"]);
            })
            ->make(true);
    }

    /**
     * Fetch item group
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function fetchItemGroups()
    {
        $item_groups = $this->item_group_api->getByColumn('name', 'id');

        return response()->json(['item_groups' => $item_groups]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('item-groups.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect()->route('item-groups.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->item_group_api->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('item-groups.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return redirect()->route('item-groups.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->item_group_api->update($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->item_group_api->destroy($id);
    }

    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required'
        ]);

        $file = $request->file('file');

        Excel::import(new ItemGroupImport, $file, null, \Maatwebsite\Excel\Excel::XLSX);

        return redirect()->route('item-groups.index');
    }

    public function getSelect2Data()
    {
        $groups = $this->item_group_api->index();

        foreach ($groups as $key => $value) {
            $data[] = [
                'id'   => $value->id,
                'text' => $value->name,
            ];
        }

        return $data;
    }
}

resources/views/item-groups/_form.blade.php
{{-- item-groups/_form.blade.php --}}

<div class="form-group mt-lg" id="div-name">
	<label class="col-sm-3 control-label text-right">Nama</label>
	<div class="col-sm-9">
		<input type="text" id="name" name="name" class="form-control" required autofocus>
		<span class="help-block text-muted">Wajib diisi</span>
		<span class="help-block text-error" id="error-name"></span>
	</div>
</div>

<div class="form-group mt-lg" id="div-description">
	<label class="col-sm-3 control-label text-right">Deskripsi</label>
	<div class="col-sm-9">
		<textarea name="description" id="description" class="form-control"></textarea>
		<span class="help-block text-error" id="error-description"></span>
	</div>
</div>

<hr>

<div class="form-group mt-lg" id="div-parent_id">
	<label class="col-sm-3 control-label text-right">Induk kategori</label>
	<div class="col-sm-9">
		<select class="form-control" id="parent_id" name="parent_id">
			<option value="">Induk kategori ...</option>
		</select>

		<span class="help-block text-muted">Pilih kategori induk jika kamu membuat subkategori.</span>
		<span class="help-block text-error" id="error-parent_id"></span>
	</div>
</div>

resources/views/item-groups/create.blade.php
{{-- item-groups/create.blade.php --}}

@component('components.modal', [
	'modal_id'    => 'modal-add-item-group',
	'modal_title' => 'tambah kategori produk',
])
	@slot('modal_body')
		<form method="post" action="{{ route('item-groups.store') }}" id="form-add-item-group">
			@csrf
			@include('item-groups._form')
		</form>
	@endslot

	@slot('modal_button')
		<button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
		<button type="submit" class="btn btn-primary" id="btn-add-item-group"><span class="fa fa-save"></span> {{ ucwords(__('simpan')) }}</button>
	@endslot
@endcomponent

resources/views/item-groups/destroy.blade.php
{{-- item-groups/destroy.blade.php --}}

@component('components.modal', [
	'modal_id'    => 'modal-destroy-item-group',
	'modal_title' => 'hapus kategori produk',
])
	@slot('modal_body')
		<form method="post" action="{{ route('item-groups.destroy', 0) }}" id="form-destroy-item-group">
			@csrf
			@method('DELETE')

			<p>Apakah kamu yakin ingin menghapus kategori <span id="item-group-name"></span>?</p>
	@endslot

	@slot('modal_button')
			<button type="button" class="btn btn-primary" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
			<button type="button" class="btn btn-default" id="btn-destroy-item-group"><span class="fa fa-trash-o"></span> {{ ucwords(__('hapus data')) }}</button>
		</form>
	@endslot
@endcomponent

resources/views/item-groups/edit.blade.php
{{-- item-groups/edit.blade.php --}}

@component('components.modal', [
	'modal_id'    => 'modal-edit-item-group',
	'modal_title' => 'perbarui informasi kategori produk',
])
	@slot('modal_body')
		<form method="put" action="{{ route('item-groups.update', 0) }}" id="form-edit-item-group">
			@csrf
			@include('item-groups._form')
	@endslot

	@slot('modal_button')
			<button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('batal')) }}</button>
			<button type="button" class="btn btn-primary" id="btn-edit-item-group"><span class="fa fa-edit"></span> {{ ucwords(__('perbarui')) }}</button>
		</form>
	@endslot
@endcomponent

resources/views/item-groups/import.blade.php
{{-- item-groups/import.blade.php --}}

@component('components.modal', [
    'modal_id'    => 'item-groups-import-modal',
    'modal_title' => 'impor kategori produk'
])
    @slot('modal_body')
        <form action="{{ route('import.item-groups') }}" method="post" id="item-group-import-form" enctype="multipart/form-data">
            @csrf

            <div class="form-group" id="div-file">
                <label for="file" class="col-sm-3 control-label text-right">
                    {{ ucfirst(__('file excel')) }}
                </label>

                <div class="col-sm-9">
                    <input type="file" name="file" id="file">
                </div>
            </div>
    @endslot

    @slot('modal_button')
            <button type="button" class="btn btn-default" data-dismiss="modal">
                <span class="fa fa-arrow-circle-left"></span>
                {{ ucwords(__('batal')) }}
            </button>

            <button type="submit" class="btn btn-primary" id="btn-import-item">
                <span class="fa fa-database"></span>
                {{ ucwords(__('import')) }}
            </button>
        </form>
    @endslot
@endcomponent

resources/views/item-groups/index.blade.php
{{-- item-groups/index.blade.php --}}

@extends('layouts.dashboard', ['page_title' => 'manajemen produk'])

@section('content')
	<p class="lead">
		Di sini kamu dapat mengatur kategori produk yang kamu sediakan.
		Kamu dapat melihat daftar semua kategori, menambahkan
		kategori baru, dan memperbarui informasi kategori produk.
	</p>

    @component('components.panel', ['panel_title' => 'daftar kategori produk'])
        <!-- start: toolbar -->
        <div class="row mb-md">
            <!-- start: left toolbar -->
            <div class="col-md-6">
                <button class="btn btn-primary" data-toggle="modal" data-target="#modal-add-item-group" data-backdrop="static" data-keyboard="false">
                    <span class="fa fa-plus"></span>
                    {{ ucwords(__('tambah kategori')) }}
                </button>

                <div class="btn-group">
                    <a href="{{ route('sales.create') }}" class="btn btn-default">
                        <span class="fa fa-print"></span>
                        {{ ucwords(__('gawe faktur')) }}
                    </a>

                    <a href="{{ route('incoming-goods.create') }}" class="btn btn-default">
                        <span class="fa fa-truck"></span>
                        {{ ucwords(__('barang datang')) }}
                    </a>
                </div>
            </div>
            <!-- end: left toolbar -->

            <!-- start: right toolbar -->
            <div class="col-md-6 text-right">

            </div>
            <!-- end: right toolbar -->
        </div>
        <!-- end: toolbar -->

		@component('components.datatable-ajax', [
			'table_id'      => 'item-groups',
			'table_headers' => ['induk kategori', 'nama kategori'],
			'condition'     => true,
			'data'          => [
				['name' => 'parent_name', 'data' => 'parent_name'],
				['name' => 'name', 'data' => 'name']
			],
			'renders'       => [
				['text_align' => 'text-right', 'column_target' => '3']
			],
		])
			@slot('data_send_ajax')
			@endslot
		@endcomponent

		@include('item-groups.create')
		@include('item-groups.show')
		@include('item-groups.edit')
		@include('item-groups.destroy')
	@endcomponent
@endsection

@push('vendorstyles')
	<link href="{{ asset('assets/vendor/select2/select2.css') }}" rel="stylesheet" type="text/css">
	<link href="{{ asset('assets/vendor/pnotify/pnotify.custom.css') }}" rel="stylesheet" type="text/css">
@endpush

@push('vendorscripts')
	<script src="{{ asset('assets/vendor/select2/select2.js') }}" type="text/javascript"></script>
	<script src="{{ asset('assets/vendor/pnotify/pnotify.custom.js') }}" type="text/javascript"></script>
@endpush

@push('appscripts')
	<script type="text/javascript">
		$(document).ready(function () {
			/* Tidak boleh menggunakan tombol enter pada form. */
			$('form').bind("keypress", function(event) {
				if (event.keyCode == 13 || event.which == 13) {
					event.preventDefault();
				}
			});

			/* Mengambil semua kategori induk. */
			function fetch_item_groups(form, selected, disabled) {
				$.ajax({
					url:    '{{ route('api.item-groups.index') }}',
					method: 'GET',

					success: function(response) {
						$('select[name="parent_id"]', form).empty();

						$('select[name="parent_id"]', form).append($('<option value="">Pilih kategori induk ...</option>'));

						$.each(response.data, function(key, value) {
							if (key == disabled) {
								$('select[name="parent_id"]', form).append($('<option value="' + value.id + '" disabled>' + value.name + '</option>'));
							}
							else {
								$('select[name="parent_id"]', form).append($('<option value="' + value.id + '">' + value.name + '</option>'));
							}
						});

						if (selected) {
							$('select[name="parent_id"]', form).val(selected).trigger('change');
						}

						$('select[name="parent_id"]', form).select2({
							dropdownParent: $(form)
						});
					},

					error: function(response) {
						new PNotify({
							type:  'warning',
							title: 'Peringatan!',
							text:  'Terdapat kesalahan saat mengambil data kategori produk',
						});
					}
				});
			}

			/* Menampilkan induk kategori pada formulir penambahan resource. */
			$('#modal-add-item-group').on('shown.bs.modal', function() {
				cleanModal('#form-add-item-group', true);
				fetch_item_groups('#form-add-item-group', null, null);
			});

			/* Memproses submisi formulir penambahan resource. */
			$('#btn-add-item-group').click(function() {
				var form = $('#form-add-item-group');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function(response) {
						$('#modal-add-item-group').modal('hide');

						table.ajax.reload();

						new PNotify({
							type:  'success',
							title: 'Sukses!',
							text:  'Kategori produk ' + response.data.name + ' berhasil ditambahkan.',
						});
					},

					error: function(response) {
						if (response.status == 422) {
							var errors = response.responseJSON;

							new PNotify({
								type:  'warning',
								title: 'Peringatan!',
								text:  'Terdapat kesalahan pada data yang dimasukkan',
							});

							cleanModal('#form-add-item-group', false);

							$.each(errors.errors, function(col_val, msg){
								$('#div-' + col_val).addClass('has-error');
								$('#error-' + col_val).html(msg[0]);
							});
						}
						else {
							systemError();
						}
					}
				});
			});

			/* Menampilkan modal untuk melihat detail data resource. */
			$('#item-groups-table tbody').on('click', 'button[name="btn-show-item-group"]', function() {
				var data = table.row($(this).closest('tr')).data();

				$('#show-item-group-title', '#modal-show-item-group').empty();
				$('#show-item-group-description', '#modal-show-item-group').empty();

				$('#show-item-group-description', '#modal-show-item-group').append(data.description);

				if (null !== data.parent_name) {
					$('#show-item-group-title', '#modal-show-item-group').append(data.parent_name + ' > ' + data.name);
				}
				else {
					$('#show-item-group-title', '#modal-show-item-group').append(data.name);
				}

				$('#modal-show-item-group').modal('show');
			});

			/* Menampilkan formulir pengubahan data resource. */
			$('#item-groups-table tbody').on('click', 'button[name="btn-edit-item-group"]', function() {
				$('#modal-edit-item-group').modal({backdrop: "static", keyboard: false});

				var data     = table.row($(this).closest('tr')).data();
				var selected = null;

				$.each($('input, select, textarea', '#form-edit-item-group'), function() {
					if ($(this).attr('id')) {
						var id_element = $(this).attr('id');

						if (data[id_element]) {
							$('#' + id_element, '#form-edit-item-group').val(data[id_element]).trigger('change');
						}
						else {
							$('#' + id_element, '#form-edit-item-group').val('').trigger('change');
						}

						if (id_element == 'parent_id') {
							selected = data[id_element];
						}
					}
				});

				cleanModal('#form-edit-item-group', false);
				fetch_item_groups('#form-edit-item-group', selected, $(this).data('id') - 1);

				$('#form-edit-item-group').attr('action', APP_URL + '/item-groups/' + $(this).data('id'));
				$('#modal-edit-item-group').modal('show');
			});

			/* Memproses data submisi pengubahan resource. */
			$('#btn-edit-item-group').click(function () {
				var form = $('#form-edit-item-group');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function(response) {
						$('#modal-edit-item-group').modal('hide');

						table.ajax.reload();

						new PNotify({
							type:  'success',
							title: 'Berhasil!',
							text:  'Informasi kategori produk ' + response.data.name + ' berhasil diperbarui.',
						});
					},

					error: function(response) {
						if (response.status == 422) {
							var errors = response.responseJSON;

							new PNotify({
								type:  'warning',
								title: 'Peringatan!',
								text:  'Terdapat kesalahan pada data yang dimasukkan',
							});

							cleanModal('#form-edit-item-group', false);

							$.each(errors.errors, function(col_val, msg) {
								$('#div-' + col_val, '#form-edit-item-group').addClass('has-error');
								$('#error-' + col_val, '#form-edit-item-group').html(msg[0]);
							});
						}
						else {
							systemError();
						}
					}
				});
			});

			/* Menampilkan formulir penghapusan resource. */
			$('#item-groups-table tbody').on('click', 'button[name="btn-destroy-item-group"]', function() {
                // Ambil data company dari baris tombol yang ditekan.
				var data = table.row($(this).closest('tr')).data();

                $('#form-destroy-item-group #item-group-name').text(data.name);

				$('#form-destroy-item-group').attr('action', APP_URL + '/item-groups/'+ $(this).data('id'));
				$('#modal-destroy-item-group').modal('show');
			});

			/* Memproses data submisi penghapusan resource. */
			$('#btn-destroy-item-group').click(function () {
				var form = $('#form-destroy-item-group');

				$.ajax({
					url:    form.attr('action'),
					method: form.attr('method'),
					data:   form.serialize(),

					success: function(response) {
						$('#modal-destroy-item-group').modal('hide');

						if (response.status == 'success') {
							new PNotify({
								type:  'success',
								title: 'Berhasil!',
								text:   response.message,
							});

							table.ajax.reload();
						}
						else {
							new PNotify({
								type:  'warning',
								title: 'Peringatan!',
								text:  response.message,
							});
						}
					},

					error: function(response) {
						systemError();
					}
				});
			});
		});
	</script>
@endpush

resources/views/item-groups/show.blade.php
{{-- item-groups/show.blade.php --}}

@component('components.modal', [
    'modal_id'     => 'modal-show-item-group',
    'modal_title'  => 'detail informasi kategori produk',
])
    @slot('modal_body')
        <h5 id="show-item-group-title"></h5>

        <div class="mt-lg" id="show-item-group-description"></div>
    @endslot

    @slot('modal_button')
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-arrow-circle-left"></span> {{ ucwords(__('tutup')) }}</button>
    @endslot
@endcomponent